ch_cookie_consent:
    categories: ['analytics', 'tracking']
    theme: 'light' # light, dark
    position: 'bottom' # top, bottom
    simplified: true # When set to true the user can only deny or accept all cookies at once
